"""Add role column to users

Revision ID: 53740683bf0d
Revises: 6e8bfb3391e6
Create Date: 2025-11-10 16:22:20.608526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53740683bf0d'
down_revision: Union[str, Sequence[str], None] = '6e8bfb3391e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_global', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column(
    'users',
    sa.Column(
        'role',
        sa.Enum('ADMIN', 'USER', name='userrole'),
        nullable=False,
        server_default='USER'
    )
)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('documents', 'is_global')
    # ### end Alembic commands ###
